import { defineConfig } from 'cspell';

export default defineConfig({
  version: '0.2',
  language: 'en',
  useGitignore: true,
  showSuggestions: true,
  showContext: true,
  files: [
    '{src,content}/**/*.{ts,tsx,js,jsx,mjs,md,mdx,json,yaml}',
    'README.md',
  ],
  words: [
    'armadactl',
    'armadaproject',
    'slurm',
    'fumadocs',
    'katex',
    'gitter',
    'unported',
    'LGBTQ',
    'Metaflow',
    'reprioritize',
    'reprioritizing',
    'xzvf',
    'golangci-lint',
    'sqlc',
    'localdev',
    'mattn',
    'richgross',
    'Goreman',
    'Procfile',
    'procfiles',
    'pprof',
    'magefiles',
    'executorapi',
    'eventingester',
    'lookoutingester',
    'lookoutui',
    'gresearch',
    'letsencrypt',
    'mymaster',
    'addrs',
    'dbname',
    'tolerations',
    'configmap',
    'podspec',
    'replayability',
    'idempotently',
    'preemptibility',
    'krew',
    'uncordon',
  ],
});
