name: Build and Deploy Website to GitHub Pages

on:
  workflow_dispatch:   # Allows you to run this workflow manually from the Actions tab
  push: # Runs on pushes targeting the default branch
    branches:
      - master
      - move-website
    paths:
      - '.github/workflows/deploy-website.yml'
      - 'docs/**'
      - 'website/**'

permissions: # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
  contents: read
  pages: write
  id-token: write

concurrency: # Allow one concurrent deployment
  group: "pages"
  cancel-in-progress: true

defaults: # Default to bash
  run:
    shell: bash

jobs:
  build: # Build job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set 'has_pages' to output
        id: has-pages
        run: echo "has_pages=$(gh api repos/${{ github.repository }} --jq .has_pages)" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare website/ for build
        run: |
          # Update _config.yml for forked repositories
          if [ "${{ github.event.repository.fork }}" == "true" ]; then
            echo "Updating _config.yml to work on forked repositories..."
            sed -i "s/^url: .*/url: \"https:\/\/${{ github.repository_owner }}.github.io\"/" _config.yml
            sed -i "s/^baseurl: .*/baseurl: \"\/$(basename ${{ github.repository }})\/\"/" _config.yml
            cat _config.yml
            echo "_config.yml updated!"
          else
            echo "Skip updating _config.yml for non-forked repositories."
          fi
          # Copy files
          echo "Copying files..."
          ./copy.sh
          echo "Files copied!"
        working-directory: ./website

      - name: Setup Pages
        uses: actions/configure-pages@v5
        if: github.ref == 'refs/heads/move-website' && steps.has-pages.outputs.has_pages == 'true'

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./website
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        if: github.ref == 'refs/heads/move-website' && steps.has-pages.outputs.has_pages == 'true'

  deploy: # Deployment job
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    #    if: github.ref == 'refs/heads/move-website' && needs.build.outputs.has_pages == 'true'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
